// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamApplication.Data;

namespace TeamApplication.Migrations
{
    [DbContext(typeof(SementesApplicationContext))]
    [Migration("20200826153436_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TeamApplication.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressKind")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Complement")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("varchar(9)")
                        .HasMaxLength(9);

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("TeamApplication.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("TeamApplication.Models.Entity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("MaxVolunteer")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("VisitDay")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("VisitDuration")
                        .HasColumnType("time");

                    b.Property<int>("VisitScale")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("datetime");

                    b.HasKey("EntityId");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("TeamApplication.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActionKind")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JobDay")
                        .HasColumnType("datetime");

                    b.Property<char>("JobPeriod")
                        .HasColumnType("int")
                        .HasMaxLength(1);

                    b.Property<int>("MaxVolunteer")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("EntityId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("TeamApplication.Models.Schedule", b =>
                {
                    b.Property<int>("TeamScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("TSDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TSPeriod")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1);

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("TeamScheduleId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("TeamApplication.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("UFAbreviation")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("UFName")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("TeamApplication.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("TeamId");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Team");
                });

            modelBuilder.Entity("TeamApplication.Models.TeamVolunteer", b =>
                {
                    b.Property<int>("TeamVolunteerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.HasKey("TeamVolunteerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("TeamVolunteer");
                });

            modelBuilder.Entity("TeamApplication.Models.Volunteer", b =>
                {
                    b.Property<int>("VolunteerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("VActive")
                        .HasColumnType("bit");

                    b.Property<int>("VAge")
                        .HasColumnType("int");

                    b.Property<DateTime>("VBirthDate")
                        .HasColumnType("datetime");

                    b.Property<string>("VDocCPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("VDocRG")
                        .IsRequired()
                        .HasColumnType("varchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("VEmail")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("VMessagePhone")
                        .HasColumnType("bit");

                    b.Property<string>("VName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("VPhone")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("VResumee")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("VSocialMidiaProfile")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("VolunteerId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Volunteer");
                });

            modelBuilder.Entity("TeamApplication.Models.Address", b =>
                {
                    b.HasOne("TeamApplication.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamApplication.Models.City", b =>
                {
                    b.HasOne("TeamApplication.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamApplication.Models.Job", b =>
                {
                    b.HasOne("TeamApplication.Models.Entity", "Entity")
                        .WithMany("Jobs")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamApplication.Models.Schedule", b =>
                {
                    b.HasOne("TeamApplication.Models.Volunteer", "Volunteer")
                        .WithMany("TeamSchedules")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamApplication.Models.Team", b =>
                {
                    b.HasOne("TeamApplication.Models.Job", "Job")
                        .WithOne("Team")
                        .HasForeignKey("TeamApplication.Models.Team", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamApplication.Models.TeamVolunteer", b =>
                {
                    b.HasOne("TeamApplication.Models.Team", "Team")
                        .WithMany("TeamVolunteer")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamApplication.Models.Volunteer", "Volunteer")
                        .WithMany("TeamVolunteer")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamApplication.Models.Volunteer", b =>
                {
                    b.HasOne("TeamApplication.Models.Address", "Address")
                        .WithOne("Volunteer")
                        .HasForeignKey("TeamApplication.Models.Volunteer", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamApplication.Models.Team", null)
                        .WithMany("Volunteers")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
